title: Stephen Boakye Frempong
logo: Stephen.png
description: A data analyst with experience using excel for data analysis for SQL data interrogation and manupulation and Power BI for creating business intelligence report.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
